
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boadsoruhcupipftkpac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvYWRzb3J1aGN1cGlwZnRrcGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjEzNzAsImV4cCI6MjA2Mjk5NzM3MH0.eLX-o7FLndFs2UVoJMRnzFo1xCEMH0mrcyF2psSNVZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
